version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: traderpass
      POSTGRES_DB: tradesdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    build: ./services/api
    container_name: trade-api
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'
    ports:
      - 8000:8000

  consumer:
    build: ./services/consumer
    container_name: trade-consumer
    depends_on:
      - kafka
      - postgres
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: tradesdb
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: traderpass

volumes:
  pgdata:
